# Edit this file to set the Messenger's module settings programmatically instead of using the GUI
# This is regular YAML syntax. See http://docs.ansible.com/ansible/YAMLSyntax.html
# You can override these settings with ENV variables. They are commented below.

# hostname: "https://sportvobot.herokuapp.com/api/botpress-messenger/webhook" # MESSENGER_HOST

# applicationID: "1964733953770879" # MESSENGER_APP_ID
# accessToken: "EAAb66kVkhX8BAFrN4wh5nnoELHlddbKjumjH0nCqxtG4YjrlS09EZBBspveVRhCGstRFaZCnaZCt9DgiaZBYM9Lqus91q3GKOOZCAuWYuL0UHB1f4YPh39ZAsnReT9dhUn473UfrR83fnXzfwUJNZAsYHgs1437VzFCemVmk8aqZBwZDZD" # MESSENGER_ACCESS_TOKEN
# appSecret: "4a293ad9bd43ba65972b7ebacd2520e6" # MESSENGER_APP_SECRET

# verifyToken: "" # MESSENGER_VERIFY_TOKEN

# displayGetStarted: true
# greetingMessage: ""

# https://developers.facebook.com/docs/messenger-platform/messenger-profile/persistent-menu
# persistentMenuItems: []

# targetAudience: openToAll
# targetAudienceOpenToSome: ""
# targetAudienceCloseToSome: ""

# trustedDomains: []
# autoRespondGetStarted: true

# paymentTesters: []

# chatExtensionHomeUrl: ""
# chatExtensionInTest: true
# chatExtensionShowShareButton: false

enabled: true