# Edit this file to set the Messenger's module settings programmatically instead of using the GUI
# This is regular YAML syntax. See http://docs.ansible.com/ansible/YAMLSyntax.html
# You can override these settings with ENV variables. They are commented below.

# hostname: "sportvobot.herokuapp.com/" # MESSENGER_HOST

# applicationID: "1964733953770879" # MESSENGER_APP_ID
# accessToken: "EAAb66kVkhX8BAF0CJFEnQZC0egO4iAapi1eFymrmq2v8OPkqoeAi58gu3RyZCKhZBZBUV0lckrNbRbs1kwDZB3ITtPrr0ko8RmYZBIVmIiUQJTfDNpItSpJZBGpdMCCa7k1eZCUHZAaQH5Wsg4FmwMnkxk8UNSTGottm3voRvwVy2VQZDZD" # MESSENGER_ACCESS_TOKEN
# appSecret: "4a293ad9bd43ba65972b7ebacd2520e6" # MESSENGER_APP_SECRET

# verifyToken: "" # MESSENGER_VERIFY_TOKEN

# displayGetStarted: true
# greetingMessage: ""

# https://developers.facebook.com/docs/messenger-platform/messenger-profile/persistent-menu
# persistentMenuItems: []

# targetAudience: openToAll
# targetAudienceOpenToSome: ""
# targetAudienceCloseToSome: ""

# trustedDomains: []
# autoRespondGetStarted: true

# paymentTesters: []

# chatExtensionHomeUrl: ""
# chatExtensionInTest: true
# chatExtensionShowShareButton: false

enabled: true